#!/usr/bin/env bash
# new-project - clone a preexisting project and set it up
#
# new-project [name]

set -euxo pipefail

# Where is this script?
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# github user or organization
OWNER="$1"

#repository belonging to $OWNER
REPO="$2"

#branch to deploy
BRANCH="$3"

git clone "git@github.com:$OWNER/$REPO.git" --branch "${BRANCH:-master}"

pushd "$MYDIR"

git submodule update --init --recursive

popd

python3 "$MYDIR/virtualenv/virtualenv.py" "$REPO/venv"

cd "$REPO"

set +u
source venv/bin/activate
set -u

pip install -r requirements.txt

deactivate
