#!/usr/bin/env bash
# new-project - clone a preexisting project and set it up
#
# new-project [name]

set -euxo pipefail

# Where is this script?
mydir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# github user or organization
owner="$1"

#repository belonging to $owner
repo="$2"

#branch to deploy
branch="$3"

git clone "git@github.com:$owner/$repo.git" --branch "${branch:-master}"

pushd "$mydir"

git submodule update --init --recursive

popd

python3 "$mydir/virtualenv/virtualenv.py" "$repo/venv"

cd "$repo"

set +u
source venv/bin/activate
set -u

pip install -r requirements.txt

deactivate
