#!/usr/bin/env bash
# new-project - clone a preexisting project and set it up
#
# new-project [name]

set -euxo pipefail

# Where is this script?
MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# only polestar at the moment
ENV="$1"

# github user or organization
OWNER="$2"

#repository belonging to $OWNER
REPO="$3"

#branch to deploy
BRANCH="$4"

git clone "git@github.com:$OWNER/$REPO.git" --branch "${BRANCH:-master}"

case $(echo ${ENV} | tr '[:upper:]' '[:lower:]') in
  polestar) module add python/3.5;;
  openmind) echo "ERROR: openmind not yet supported" && exit 1;;
  *) echo "ERROR: ${ENV} not supported" && exit 1;;
esac

pushd "$MYDIR"

git submodule update --init --recursive

popd

python3 "$MYDIR/virtualenv/virtualenv.py" "$REPO/venv"

cd "$REPO"

set +u
source venv/bin/activate
set -u

pip install -r requirements

deactivate
