#!/usr/bin/env bash
# new-project - clone the CBMM project template and name it
#
# new-project [name]

set -euxo pipefail

NAME="$1"

git clone git@github.com:CBMM/tensorflow-template.git "$NAME"
cd "$NAME"

git remote remove origin

git mv project "$NAME"

sed -i "s/project/$NAME/g" "$NAME"/*
sed -i "s/project/$NAME/g" tests/*

git commit -a -m "'Initialize project $NAME from template'"

if [ -z ${NIX_PATH+x} ]
then
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt -I
pip install nose2 -I
deactivate
fi
